[project]
name = "magisysteme3"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.42.16",
    "python-dotenv>=1.2.1",
    "streamlit>=1.52.2",
]
